USER_LIB_PATH = ../libs

BOARD_TAG = mini
BOARD_SUB = atmega328

ISP_PROG  = stk500v1
ISP_PORT  = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE = 19200

SKETCH = flask.cpp

include ../libs/Arduino-Makefile/Arduino.mk
